# Generated by Django 4.2.6 on 2023-12-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colreg',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
