# Generated by Django 4.2.6 on 2023-12-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0003_compreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('travelid', models.CharField(max_length=20)),
                ('phoneno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('lisence', models.FileField(upload_to='')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
