# Generated by Django 4.2.6 on 2023-12-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0004_travelreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='compreg',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelreg',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
