# Generated by Django 4.2.6 on 2023-12-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0005_compreg_status_travelreg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='collegedept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('coldepartment', models.CharField(max_length=15)),
                ('noofstudents', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='compreg',
            name='location',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
