# Generated by Django 5.0 on 2023-12-19 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0006_collegedept_compreg_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedept',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ivapp.colreg'),
        ),
    ]
