# Generated by Django 5.0 on 2023-12-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0007_alter_collegedept_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colreg',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='compreg',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='travelreg',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
