# Generated by Django 5.0 on 2024-01-03 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0008_alter_colreg_username_alter_compreg_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cabout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special', models.CharField(max_length=40, null=True)),
                ('native', models.CharField(max_length=40)),
                ('achievements', models.CharField(max_length=40, null=True)),
                ('fprice', models.IntegerField(null=True)),
                ('disc', models.TextField(null=True)),
                ('experience', models.IntegerField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ivapp.travelreg')),
            ],
        ),
        migrations.CreateModel(
            name='comppro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('projectimage', models.FileField(max_length=20, upload_to='')),
                ('client', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('projectdetail', models.TextField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ivapp.travelreg')),
            ],
        ),
    ]
