# Generated by Django 5.0 on 2024-01-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0010_rename_name_cabout_tname_rename_name_comppro_tname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compreg',
            name='profile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='travelreg',
            name='profile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
