# Generated by Django 5.0 on 2024-01-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0011_compreg_profile_travelreg_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabout',
            name='special',
        ),
    ]
