# Generated by Django 5.0 on 2024-01-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0012_remove_cabout_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabout',
            name='experience',
        ),
    ]
