# Generated by Django 5.0 on 2024-01-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0013_remove_cabout_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comppro',
            old_name='category',
            new_name='collegename',
        ),
        migrations.RenameField(
            model_name='comppro',
            old_name='client',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='comppro',
            old_name='projectdetail',
            new_name='projectdescr',
        ),
        migrations.RenameField(
            model_name='comppro',
            old_name='projectimage',
            new_name='projectimg',
        ),
    ]
