# Generated by Django 4.2.7 on 2024-01-20 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0015_collegedept_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedept',
            name='cname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ivapp.compreg'),
        ),
    ]
