# Generated by Django 5.0.1 on 2024-01-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0017_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedept',
            name='fprice',
            field=models.IntegerField(null=True),
        ),
    ]
