# Generated by Django 5.0.1 on 2024-01-29 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0018_collegedept_fprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegedept',
            name='duration',
        ),
    ]
