# Generated by Django 5.0.1 on 2024-01-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0019_remove_collegedept_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedept',
            name='paid',
            field=models.CharField(default='Not Paid', max_length=10),
        ),
    ]
