# Generated by Django 5.0.1 on 2024-02-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0021_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colreg',
            name='collegeid',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='compreg',
            name='compid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
