# Generated by Django 5.0.1 on 2024-02-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0022_alter_colreg_collegeid_alter_compreg_compid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comppro',
            name='tname',
        ),
        migrations.RemoveField(
            model_name='cabout',
            name='tname',
        ),
        migrations.RemoveField(
            model_name='compreg',
            name='location',
        ),
        migrations.DeleteModel(
            name='travelreg',
        ),
    ]
