# Generated by Django 5.0.1 on 2024-02-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0023_remove_comppro_tname_remove_cabout_tname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colreg',
            name='profile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
