# Generated by Django 5.0.1 on 2024-02-01 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0024_colreg_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colreg',
            name='password',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password must contain at least one digit, one uppercase letter, one lowercase letter, and one special character.', regex='^(?=.\\d)(?=.[a-z])(?=.[A-Z])(?=.[!@#$%^&*()_+}{":;\']).{8,}$')]),
        ),
    ]
