# Generated by Django 5.0.1 on 2024-02-06 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0025_alter_colreg_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='compreg',
            name='addr',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='comname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ivapp.compreg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cabout',
            name='native',
            field=models.TextField(),
        ),
    ]
