# Generated by Django 5.0.1 on 2024-02-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0026_compreg_addr_reviews_comname_alter_cabout_native'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedept',
            name='time',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
