# Generated by Django 5.0.1 on 2024-02-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivapp', '0027_collegedept_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='comname',
            field=models.CharField(max_length=40),
        ),
    ]
